package config

import (
	"bytes"
	"fmt"
	"text/template"
)

// TemplateOptions controls `circa config init`'s generated YAML (DESIGN/08
// §8.1.2): --profile picks a preset, everything else is a targeted override
// applied on top of it.
type TemplateOptions struct {
	Profile         string // "minimal" (default) or "full"
	ListenAddress   string
	Hostname        string // host:port for an *additional* scrape target's URL; empty (the default) means none
	RetentionRaw    string
	RetentionMinute string
	RetentionHour   string
}

// DefaultTemplateOptions is the "minimal" profile: local self-collection +
// storage + UI only, every other optional subsystem off — the same
// defaults Default() uses. Hostname is deliberately left empty: as of
// v0.5.0 circa monitors its own host out of the box (features.collect), so
// there's no longer a default node_exporter target to pre-populate — a
// scrape target is something you *add* for another host/exporter, not a
// prerequisite for circa to show anything. See RELEASE/v0.5.0.md.
func DefaultTemplateOptions() TemplateOptions {
	return TemplateOptions{
		Profile:         "minimal",
		ListenAddress:   ":9100",
		RetentionRaw:    "2h",
		RetentionMinute: "7d",
		RetentionHour:   "365d",
	}
}

// templateData is what the template actually executes against — embeds
// TemplateOptions plus fields derived from it (Full) or from package-level
// anomaly defaults, so the template stays a straight field reference with
// no expression logic in the template text itself.
type templateData struct {
	TemplateOptions
	Full                   bool
	AnomalyModelCount      int
	AnomalyTrainingWindow  string
	AnomalyRetrainInterval string
	AnomalyDiffN           int
	AnomalySmoothN         int
	AnomalyLagN            int
	AnomalyScoreThreshold  float64
}

// GenerateTemplate renders a fully-commented, ready-to-run config.yaml.
// "full" turns every feature flag on (with placeholder backup/push
// endpoints) for evaluation/demo purposes; "minimal" leaves them all off.
func GenerateTemplate(opts TemplateOptions) (string, error) {
	if opts.Profile == "" {
		opts.Profile = "minimal"
	}
	if opts.Profile != "minimal" && opts.Profile != "full" {
		return "", fmt.Errorf("unknown profile %q (want \"minimal\" or \"full\")", opts.Profile)
	}

	def := DefaultTemplateOptions()
	if opts.ListenAddress == "" {
		opts.ListenAddress = def.ListenAddress
	}
	// opts.Hostname is intentionally NOT defaulted here (unlike every other
	// field) — empty means "no additional scrape target," which is the
	// correct default now that self-collection covers the local host. Only
	// an explicit --hostname should produce a target entry.
	if opts.RetentionRaw == "" {
		opts.RetentionRaw = def.RetentionRaw
	}
	if opts.RetentionMinute == "" {
		opts.RetentionMinute = def.RetentionMinute
	}
	if opts.RetentionHour == "" {
		opts.RetentionHour = def.RetentionHour
	}

	tmpl := template.Must(template.New("config").Parse(configTemplate))
	var buf bytes.Buffer
	data := templateData{
		TemplateOptions:        opts,
		Full:                   opts.Profile == "full",
		AnomalyModelCount:      DefaultModelCount,
		AnomalyTrainingWindow:  Duration(DefaultTrainingWindow).String(),
		AnomalyRetrainInterval: Duration(DefaultRetrainInterval).String(),
		AnomalyDiffN:           DefaultDiffN,
		AnomalySmoothN:         DefaultSmoothN,
		AnomalyLagN:            DefaultLagN,
		AnomalyScoreThreshold:  DefaultScoreThreshold,
	}
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

const configTemplate = `# Circa configuration - generated by "circa config init --profile {{.Profile}}".
# Copy to config.yaml (already done if you didn't pass --output), then:
#   circa -config config.yaml
#
# Circa is a self-monitoring single binary: with no config at all it already
# collects its own host's cpu/memory/disk/network (features.collect, see
# RELEASE/v0.5.0.md) - nothing below is required to see something in the
# dashboard. Anything under a feature's own key (alerting/backup/
# ingest.influx/push/*) is only read if that feature's flag is true - see
# DESIGN/08_design_config_auth_ops.md. ingest.scrape is the exception: it
# always runs, an empty target list just means no *additional* hosts are
# scraped beyond what circa collects about itself.

server:
  listen_address: "{{.ListenAddress}}"

features:
  collect: true              # built-in local system metrics - the zero-config default (v0.5.0)
  ml: {{.Full}}             # anomaly detection - CPU-hungry, off by default
  alerts: {{.Full}}          # rule engine + notifications
  backup: {{.Full}}          # CDC export to Iceberg
  influx_receive: {{.Full}}  # accept InfluxDB line protocol from Telegraf
  push_receive: {{.Full}}    # accept incoming remote_write pushes
  push_send: {{.Full}}       # push ingested metrics onward

ingest:
  collect:                       # only read if features.collect is true (default true)
    interval: 15s
  scrape:                        # always on; empty targets = nothing extra beyond self-collection
{{- if .Hostname}}
    targets:
      - url: http://{{.Hostname}}/metrics
        interval: 15s
        labels: { job: node }
{{- else}}
    targets: []
    # add entries here to scrape another host or exporter, e.g.:
    # targets:
    #   - url: http://node2:9100/metrics
    #     interval: 15s
    #     labels: { job: node }
{{- end}}
  influx:              # only read if features.influx_receive is true
    path: /write

storage:
  path: /var/lib/circa/data
  retention:
    raw: {{.RetentionRaw}}
    minute: {{.RetentionMinute}}
    hour: {{.RetentionHour}}

alerting:            # only read if features.alerts is true
{{- if .Full}}
  rules:
    - name: high_cpu
      metric: node_cpu_seconds_total
      labels: { mode: idle }
      condition: { type: threshold, operator: "<", value: 10 }
      for: 5m
      severity: warning
      notify: [ops-webhook]
  notifiers:
    - name: ops-webhook
      type: webhook
      url: https://example.internal/circa-alerts
{{- else}}
  rules: []
  notifiers: []
{{- end}}

anomaly:              # only read if features.ml is true - DESIGN/06 §6.2,
                      # DESIGN/10_ml_summary.md (defaults match Netdata's own)
  model_count: {{.AnomalyModelCount}}            # ensemble size per metric
  training_window: {{.AnomalyTrainingWindow}}    # history each new model trains on
  retrain_interval: {{.AnomalyRetrainInterval}}  # how often a new model joins the ensemble
  diff_n: {{.AnomalyDiffN}}                      # order of differencing (0 or 1)
  smooth_n: {{.AnomalySmoothN}}                  # rolling-average window after differencing
  lag_n: {{.AnomalyLagN}}                        # lagged values per feature vector
  score_threshold: {{.AnomalyScoreThreshold}}    # 0..100 - anomaly score cutoff

backup:               # only read if features.backup is true
  mode: pull           # push | pull
  schedule: "*/15 * * * *"
  catalog:
    uri: https://iceberg-catalog.internal:8181
    warehouse: s3://metrics-lake/circa

push:
  receive:            # only read if features.push_receive is true
    path: /api/v1/write
  send:                # only read if features.push_send is true
    url: https://central-receiver.internal/api/v1/write
    interval: 30s

auth:
  # absent or empty = no auth (default) - fine for localhost/trusted networks.
  # Use "circa auth add-user <name>" to add entries here rather than
  # hand-editing - it bcrypt-hashes the password for you.
  users: {}
`
