package config

import (
	"bytes"
	"fmt"
	"text/template"
)

// TemplateOptions controls `circa config init`'s generated YAML (DESIGN/08
// §8.1.2): --profile picks a preset, everything else is a targeted override
// applied on top of it.
type TemplateOptions struct {
	Profile         string // "minimal" (default) or "full"
	ListenAddress   string
	Hostname        string // host:port for the default scrape target's URL
	RetentionRaw    string
	RetentionMinute string
	RetentionHour   string
}

// DefaultTemplateOptions is the "minimal" profile: collection + storage + UI
// only, every optional subsystem off — the same defaults Default() uses.
func DefaultTemplateOptions() TemplateOptions {
	return TemplateOptions{
		Profile:         "minimal",
		ListenAddress:   ":9100",
		Hostname:        "localhost:9100",
		RetentionRaw:    "2h",
		RetentionMinute: "7d",
		RetentionHour:   "365d",
	}
}

// GenerateTemplate renders a fully-commented, ready-to-run config.yaml.
// "full" turns every feature flag on (with placeholder backup/push
// endpoints) for evaluation/demo purposes; "minimal" leaves them all off.
func GenerateTemplate(opts TemplateOptions) (string, error) {
	if opts.Profile == "" {
		opts.Profile = "minimal"
	}
	if opts.Profile != "minimal" && opts.Profile != "full" {
		return "", fmt.Errorf("unknown profile %q (want \"minimal\" or \"full\")", opts.Profile)
	}

	def := DefaultTemplateOptions()
	if opts.ListenAddress == "" {
		opts.ListenAddress = def.ListenAddress
	}
	if opts.Hostname == "" {
		opts.Hostname = def.Hostname
	}
	if opts.RetentionRaw == "" {
		opts.RetentionRaw = def.RetentionRaw
	}
	if opts.RetentionMinute == "" {
		opts.RetentionMinute = def.RetentionMinute
	}
	if opts.RetentionHour == "" {
		opts.RetentionHour = def.RetentionHour
	}

	tmpl := template.Must(template.New("config").Parse(configTemplate))
	var buf bytes.Buffer
	data := struct {
		TemplateOptions
		Full bool
	}{opts, opts.Profile == "full"}
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

const configTemplate = `# Circa configuration - generated by "circa config init --profile {{.Profile}}".
# Copy to config.yaml (already done if you didn't pass --output), then:
#   circa -config config.yaml
#
# Anything under a feature's own key (alerting/backup/ingest.influx/push/*) is
# only read if that feature's flag below is true - see
# DESIGN/08_design_config_auth_ops.md. ingest.scrape is the exception: it
# always runs, an empty target list just means nothing is collected.

server:
  listen_address: "{{.ListenAddress}}"

features:
  ml: {{.Full}}             # anomaly detection - CPU-hungry, off by default
  alerts: {{.Full}}          # rule engine + notifications
  backup: {{.Full}}          # CDC export to Iceberg
  influx_receive: {{.Full}}  # accept InfluxDB line protocol from Telegraf
  push_receive: {{.Full}}    # accept incoming remote_write pushes
  push_send: {{.Full}}       # push ingested metrics onward

ingest:
  scrape:                        # always on; empty targets = nothing collected
    targets:
      - url: http://{{.Hostname}}/metrics   # e.g. a co-located node_exporter
        interval: 15s
        labels: { job: node }
  influx:              # only read if features.influx_receive is true
    path: /write

storage:
  path: /var/lib/circa/data
  retention:
    raw: {{.RetentionRaw}}
    minute: {{.RetentionMinute}}
    hour: {{.RetentionHour}}

alerting:            # only read if features.alerts is true
  rules: []
  notifiers: []

backup:               # only read if features.backup is true
  mode: pull           # push | pull
  schedule: "*/15 * * * *"
  catalog:
    uri: https://iceberg-catalog.internal:8181
    warehouse: s3://metrics-lake/circa

push:
  receive:            # only read if features.push_receive is true
    path: /api/v1/write
  send:                # only read if features.push_send is true
    url: https://central-receiver.internal/api/v1/write
    interval: 30s

auth:
  # absent or empty = no auth (default) - fine for localhost/trusted networks.
  # Use "circa auth add-user <name>" to add entries here rather than
  # hand-editing - it bcrypt-hashes the password for you.
  users: {}
`
